---
- name: Set product's repository directory
  set_fact:
    product_repo_dir: "/opt/rpc-openstack"

- name: Set OSA's repo directory
  set_fact:
    oa_repo_dir: "{{ product_repo_dir }}/openstack-ansible"

- name: Create OA environment directory
  file:
    path: /etc/openstack_deploy/env.d
    state: directory
    mode: 0755

- name: Copy RPC rpcd/etc configuration files
  shell: "cp -r {{ product_repo_dir }}/rpcd/etc/openstack_deploy/* /etc/openstack_deploy/"

- name: Copy OA environment files
  shell: "cp -r {{ oa_repo_dir }}/etc/openstack_deploy/env.d/* /etc/openstack_deploy/env.d/"

- name: Copy OA secrets file
  shell: "cp -r {{ oa_repo_dir }}/etc/openstack_deploy/user_secrets.yml /etc/openstack_deploy/user_osa_secrets.yml"

- name: Ensure Cinder Ceph Client UUID secret is added for Ceph Deploys
  lineinfile:
    dest: /etc/openstack_deploy/user_rpco_secrets.yml
    line: 'cinder_ceph_client_uuid:'
  when: groups.ceph is defined

- name: Setup osa user variables file
  template:
    src: user_osa_variables_overrides.j2
    dest: /etc/openstack_deploy/user_osa_variables_overrides.yml

- name: Setup rpco user variables file
  template:
    src: user_rpco_variables_overrides.j2
    dest: /etc/openstack_deploy/user_rpco_variables_overrides.yml
  when: groups.ceph is defined

- name: Setup user configuration file
  template:
    src: user_config.j2
    dest: /etc/openstack_deploy/openstack_user_config.yml

- name: Generate OSA passphrases
  command: "{{ oa_repo_dir }}/scripts/pw-token-gen.py --file /etc/openstack_deploy/user_osa_secrets.yml"

- name: Generate RPC passphrases
  command: "{{ oa_repo_dir }}/scripts/pw-token-gen.py --file /etc/openstack_deploy/user_rpco_secrets.yml"

- name: Configure Swift
  template:
    src: swift.j2
    dest: /etc/openstack_deploy/conf.d/swift.yml
    mode: 0644
  when: groups.object is defined

- name: Configure Ceph
  template:
    src: ceph.j2
    dest: /etc/openstack_deploy/conf.d/ceph.yml
    mode: 0644
  when: groups.ceph is defined
