---
# This playbook installs Rackspace Private Cloud v13.1

- name: Do Nothing
  hosts: all
  tags:
    - prepare
  tasks:
    - name: Ping Nodes
      ping:

- name: Prepare Environment
  hosts: all:!deployment
  tags:
    - prepare
    - packages
  roles:
    - packages

- name: Setup Cinder Volume Groups
  hosts: block
  tags:
    - prepare
    - volumes
  roles:
    - volumes

- name: Setup Swift Mount Points
  hosts: object
  tags:
    - prepare
    - mounts
  roles:
    - mounts

- name: Setup Networking
  hosts: all:!deployment
  tags:
    - prepare
    - networking
  roles:
    - networking

- name: Reboot Cluster
  hosts: all:!deployment
  tags:
    - reboot
  roles:
    - reboot
